@startuml
'https://plantuml.com/class-diagram

class HeroAircraft{
    - {static} heroAircraft:HeroAircraft
    - {static} shootContext:ShootContext

    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + {static} getInstance:HeroAircraft
    + setStrategy(ShootStrategy shootStrategy):void
    + forward():void
    + shoot():List<BaseBullet>
}

class Game{}

Game --> HeroAircraft
HeroAircraft --> HeroAircraft

@enduml